version: '3.1'
services:
  spring-boot-kotlin:
    image: kotlin-project
    container_name: spring-boot-kotlin
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - cassandra
    links:
      - cassandra
    restart: always
    stdin_open: true
    tty: true

  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    expose:
      - "9042"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./cassandra-init.sh:/cassandra-init.sh"
    environment:
      CASSANDRA_BROADCAST_ADDRESS: 192.168.0.105
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]