spring:
 data:
  cassandra:
   contact-points: 192.168.0.105
   port: 9042
   keyspace-name: user_registration
   local-datacenter: datacenter1
   schema-action: create_if_not_exists
server:
 port: 9000